const {test, expect} = require('@playwright/test')
test('Clent App', async ({page}) =>  
{
  await page.goto("https://rahulshettyacademy.com/client/#/auth/login");
  await page.locator("#userEmail").fill('anshika@gmail.com');
  await page.locator("#userPassword").fill('Iamking@000');
  await page.locator("[value='Login']").click();
  await page.waitForLoadState('networkidle'); //1. Wait for the page to load, because we are asking it to wait until network is idle. // to check this, go to 'networl' -> 'fetch/xhr' to see the respone generated by the server.
  //if test is run without this line
  // tests\2ClientApp.spec.js:2:6 › Clent App -> output: [] //empty list will be returned
  //signifying that the after login it didn't wait and returned the output before the page was loaded and it returned empty list and done. so we need to wait for the page to load before getting the output.

// tests\2ClientApp.spec.js:2:6 › Clent App
// [
//   'ADIDAS ORIGINAL',
//   'ZARA COAT 3',
//   'iphone 13 pro',
//   'qwerty',
//   'qwerty',
//   'qwerty',
//   'car',
//   'iPhone QA Max',
//   '{{productName}}'
// ]
//   1 passed (6.1s) //when we let the network idle, and let it load. it worked.

//if 'networkidle' is not working, we can use 'waitForSelector' to wait for the specific element to be visible on the page. ex= await page.waitForSelector(".card-body b") - this will wait for the element with class 'card-body' and tag 'b' to be visible on the page before proceeding to the next step.

//await page.locator(".card-body b").waitFor(".card-body b") //2. wait for the element to be visible on the page before proceeding to the next step.  
//it will return many element, so we need to specify target element and then proceed.

//await page.locator(".card-body b").first().waitFor() //3. wait for the first element to be visible on the page before proceeding to the next step.

//4. playwright has autowait mechanism for 'click', 'check' etc. so we don't need to use 'waitForSelector' for these actions. but if we are using 'locator' to get the element, then we need to use 'waitForSelector' to wait for the element to be visible on the page before proceeding to the next step.

  const titles =await page.locator(".card-body b").allTextContents();
  console.log(titles);

});

//5. RADIO BUTTON & DROP DOWN SPLIT PLAYER

test('UI Controls', async({page}) =>
{
   await page.goto("https://rahulshettyacademy.com/loginpagePractise/");
  const usetName = page.locator('#username');
  const signin = page.locator('#signInBtn'); 
  const dropdown = page.locator("select.form-control");
  await dropdown.selectOption("consult");

  //6. if any execution is fast use pause s0 the execution will pause before closing the test.
  //await page.pause(); //this opens a new playwright inspector - use for debugging etc

  await page.locator(".radiotextsty").last().click();
  await page.locator("#okayBtn").click(); //7. on switching from 'admin' to 'user', we have to tap okay on the pop-up.

  //8. assertion
  await expect(page.locator(".radiotextsty").last()).toBeChecked();
  console.log(await page.locator(".radiotextsty").last().isChecked()); //boolean way of checking //not much used as it doesn't help in automation.

  //9. checking and unchecking of 'terms' condition
  await page.locator("#terms").click(); 
  await expect(page.locator("#terms")).toBeChecked(); //20. note: as the action is performed at end, await is outside the 'expect'
  await page.locator("#terms").uncheck();
  expect(await page.locator("#terms").isChecked()).toBeFalsy(); //21. unlike '20.', here await is inside scope, as the action is inside the scope. 

  //22.to check if the text is blibking, the top part on webpage
  const doc = page.locator("[href*='documents-request']")
  await expect(doc).toHaveAttribute("class", "blinkingText");

  //await page.pause();
});

test('Child Page Window', async({browser}) =>
{
  const context = await browser.newContext();
  const page = await context.newPage();
  const usernm = page.locator('#username'); //30. for '29.'
  await page.goto("https://rahulshettyacademy.com/loginpagePractise/");
  const doc = page.locator("[href*='documents-request']")

  //doc.click(); //23. upon entering this new page, our main context is still the first page- as the new page is opening in diff tab, and our browser has no context about new page created seperatly. so here we will handle this.
  //clicking 'doc' before will cause error, as it will load and search for page, which still hasn't loaded yet. so we will open the doc after opening page2
  
  //25. following will also not able to execute the page, as it won't run simultaneously, and the click won't happen

  //const page2 = context.waitForEvent('page');
  //doc.click(); //24. now new page will open.
  /*there is still some issues: since its JS, and it is asynchronous
  we will handle it using promises.
  there are 3 states of promises - 
  a. promise pending
  b. promise rejeted
  c. promise fulfiled*/

  const [newPage] = await Promise.all([ //27. this array will return no 'promise;, just a 'click' operation.
    context.waitForEvent('page'),
    doc.click(),
  ]) //26. now new page will open, as we promised it 'all' //it will need to go parallelly, asyschrnous way- when we've dependencies that multiple steps in the playwright script go asynchronously.
  
  const text = await newPage.locator(".red").textContent();
  const arrtext = text.split("@") //27. splitting the array from '@' 
  const domain = arrtext[1].split(" ")[0] //28. to get the email from right side- and just email.
  console.log(domain);
  //29. we got the 'domain' name, but now we need to add it in 'username' on first page, so use parent page again.
  await page.locator("#username").fill(domain);
  await page.pause();
  //console.log(await page.locator("#username").textContent());
  console.log(await page.locator("#username").inputValue());
  //31. This text content will return an empty because what we have written the domain is specifically over written over the dialogue box and not a valid text content in the original page it is still empty what we see as the written over there is just explicitly written by user or by program so to find or to print the actual value inside that dialogue box we can't use text content we have to use input value to check what is actually input there. 
});